name: Update Rules

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 显式声明写入权限
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: rules  # 检出 rules 分支
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create rules branch if not exists
      run: |
        git fetch origin
        git checkout rules 2>/dev/null || git checkout -b rules
        git reset --hard origin/rules 2>/dev/null || true
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Copy scripts from main
      run: |
        git fetch origin main
        git checkout origin/main -- data/python/
        git checkout origin/main -- data/mod/
        
    - name: Update rules
      run: |
        python data/python/dl.py
        python data/python/merge.py
        
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TZ: Asia/Shanghai  # 设置时区为北京时间
      run: |
        git add data/rules/
        timestamp=$(date '+%Y-%m-%d %H:%M:%S')
        git commit -m "chore: update rules - ${timestamp}（北京时间）" || exit 0
        git push origin rules 